# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ae40981d69f95a84a1826f6782600b9"
name = "New-Script-s31-GWP"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers, write_customers, read_discounts, write_discounts, read_products, write_products, read_orders, write_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]


[discount.metafields.app.gwp-s31]
type = "json"
name = "GWP configuration"
description = "Threshold & gift variant config for the GWP discount function."
access.admin = "merchant_read_write"
access.storefront = "none"